name: heat_map
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  protobuf: ^2.0.0
  fixnum: ^1.0.0
  simple_cluster: ^0.3.0
  equatable: ^2.0.0
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter: